# Generated by Django 5.1.4 on 2024-12-17 07:51

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contato_owner_alter_contato_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, default='pictures/default_avatar.png', force_min_size=False, upload_to='pictures/%Y/%m/', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}}),
        ),
    ]
