# Generated by Django 5.1.4 on 2025-01-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contato_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='telefone'),
        ),
    ]
