# Generated by Django 5.1.4 on 2025-01-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contato_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='telefone'),
        ),
    ]
